/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Sat Jul 20 22:16:26 CEST 2013 ----! */

package org.sqlg;

//import com.jogamp.gluegen.runtime.*;
//import com.jogamp.common.os.*;
//import com.jogamp.common.nio.*;
//import java.nio.*;

public class SQLiteGlue {

  public static final int SQLG_OPEN_READONLY = 1;
  public static final int SQLG_OPEN_READWRITE = 2;
  public static final int SQLG_OPEN_CREATE = 4;

  /** Interface to C language function: <br> <code> int sqlg_db_close(ptrdiff_t db); </code>    */
  public static native int sqlg_db_close(long db);

  /** Interface to C language function: <br> <code> ptrdiff_t sqlg_db_open(const char *  filename, int flags); </code>    */
  public static native long sqlg_db_open(String filename, int flags);

  /** Interface to C language function: <br> <code> ptrdiff_t sqlg_db_prepare_st(ptrdiff_t db, const char *  sql); </code>    */
  public static native long sqlg_db_prepare_st(long db, String sql);

  /** Interface to C language function: <br> <code> int sqlg_st_bind_double(ptrdiff_t st, int col, double val); </code>    */
  public static native int sqlg_st_bind_double(long st, int col, double val);

  /** Interface to C language function: <br> <code> int sqlg_st_bind_int(ptrdiff_t st, int col, int val); </code>    */
  public static native int sqlg_st_bind_int(long st, int col, int val);

  /** Interface to C language function: <br> <code> int sqlg_st_bind_int64(ptrdiff_t st, int col, ptrdiff_t val); </code>    */
  public static native int sqlg_st_bind_int64(long st, int col, long val);

  /** Interface to C language function: <br> <code> int sqlg_st_bind_text(ptrdiff_t st, int col, const char *  val); </code>    */
  public static native int sqlg_st_bind_text(long st, int col, String val);

  /** Interface to C language function: <br> <code> int sqlg_st_column_count(ptrdiff_t st); </code>    */
  public static native int sqlg_st_column_count(long st);

  /** Interface to C language function: <br> <code> const char *  sqlg_st_column_name(ptrdiff_t st, int col); </code>    */
  public static native String sqlg_st_column_name(long st, int col);

  /** Interface to C language function: <br> <code> const char *  sqlg_st_column_text(ptrdiff_t st, int col); </code>    */
  public static native String sqlg_st_column_text(long st, int col);

  /** Interface to C language function: <br> <code> int sqlg_st_column_type(ptrdiff_t st, int col); </code>    */
  public static native int sqlg_st_column_type(long st, int col);

  /** Interface to C language function: <br> <code> int sqlg_st_finish(ptrdiff_t st); </code>    */
  public static native int sqlg_st_finish(long st);

  /** Interface to C language function: <br> <code> int sqlg_st_step(ptrdiff_t st); </code>    */
  public static native int sqlg_st_step(long st);


} // end of class SQLiteGlue
