/* !---- DO NOT EDIT: This file autogenerated by com/jogamp/gluegen/JavaEmitter.java on Thu Jun 04 23:42:06 CEST 2015 ----! */

package org.sqlg;

//import com.jogamp.gluegen.runtime.*;
//import com.jogamp.common.os.*;
//import com.jogamp.common.nio.*;
//import java.nio.*;

public class SQLiteGlue {

  public static final int SQLG_OPEN_READONLY = 1;
  public static final int SQLG_OPEN_READWRITE = 2;
  public static final int SQLG_OPEN_CREATE = 4;

  /** Interface to C language function: <br> <code> int sqlg_db_close(sqlg_handle_t db); </code>    */
  public static native int sqlg_db_close(long db);

  /** Interface to C language function: <br> <code> sqlg_long_t sqlg_db_last_insert_rowid(sqlg_handle_t db); </code>    */
  public static native long sqlg_db_last_insert_rowid(long db);

  /** Interface to C language function: <br> <code> sqlg_handle_t sqlg_db_open(const char *  filename, int flags); </code>    */
  public static native long sqlg_db_open(String filename, int flags);

  /** Interface to C language function: <br> <code> sqlg_handle_t sqlg_db_prepare_st(sqlg_handle_t db, const char *  sql); </code>    */
  public static native long sqlg_db_prepare_st(long db, String sql);

  /** Interface to C language function: <br> <code> int sqlg_db_total_changes(sqlg_handle_t db); </code>    */
  public static native int sqlg_db_total_changes(long db);

  /** Interface to C language function: <br> <code> int sqlg_st_bind_double(sqlg_handle_t st, int col, double val); </code>    */
  public static native int sqlg_st_bind_double(long st, int col, double val);

  /** Interface to C language function: <br> <code> int sqlg_st_bind_int(sqlg_handle_t st, int col, int val); </code>    */
  public static native int sqlg_st_bind_int(long st, int col, int val);

  /** Interface to C language function: <br> <code> int sqlg_st_bind_int64(sqlg_handle_t st, int col, sqlg_long_t val); </code>    */
  public static native int sqlg_st_bind_int64(long st, int col, long val);

  /** Interface to C language function: <br> <code> int sqlg_st_bind_text(sqlg_handle_t st, int col, const char *  val); </code>    */
  public static native int sqlg_st_bind_text(long st, int col, String val);

  /** Interface to C language function: <br> <code> int sqlg_st_bind_text_string(sqlg_handle_t st, int col, const char *  val); </code>    */
  public static native int sqlg_st_bind_text_string(long st, int col, String val);

  /** Interface to C language function: <br> <code> int sqlg_st_column_count(sqlg_handle_t st); </code>    */
  public static native int sqlg_st_column_count(long st);

  /** Interface to C language function: <br> <code> double sqlg_st_column_double(sqlg_handle_t st, int col); </code>    */
  public static native double sqlg_st_column_double(long st, int col);

  /** Interface to C language function: <br> <code> sqlg_long_t sqlg_st_column_long(sqlg_handle_t st, int col); </code>    */
  public static native long sqlg_st_column_long(long st, int col);

  /** Interface to C language function: <br> <code> const char *  sqlg_st_column_name(sqlg_handle_t st, int col); </code>    */
  public static native String sqlg_st_column_name(long st, int col);

  /** Interface to C language function: <br> <code> const char *  sqlg_st_column_text(sqlg_handle_t st, int col); </code>    */
  public static native String sqlg_st_column_text(long st, int col);

  /** Interface to C language function: <br> <code> const char *  sqlg_st_column_text_string(sqlg_handle_t st, int col); </code>    */
  public static native String sqlg_st_column_text_string(long st, int col);

  /** Interface to C language function: <br> <code> int sqlg_st_column_type(sqlg_handle_t st, int col); </code>    */
  public static native int sqlg_st_column_type(long st, int col);

  /** Interface to C language function: <br> <code> int sqlg_st_finish(sqlg_handle_t st); </code>    */
  public static native int sqlg_st_finish(long st);

  /** Interface to C language function: <br> <code> int sqlg_st_step(sqlg_handle_t st); </code>    */
  public static native int sqlg_st_step(long st);


} // end of class SQLiteGlue
